### ISSUE TITLE
How to handle distributions that change the format of the version number?

### ISSUE THREAD

**Issue by ProgVal** [repology/libversion#17]
Hi,

For my project, I use the format `YYYY.MM.DD`. However, some distributions change it to `YYYYMMDD`, which causes Repology to consider `20171025` to be newer than `2018.06.25`, [as you can see here](https://repology.org/metapackage/limnoria/badges)

How should this be handled?

**Comment by AMDmi3** [comment]
This is definitely not related to libversion. This can be fixed either on repositories which use fake versions or in Repology by adding rules which fix the version scheme or ignore bad versions.

**Comment by AMDmi3** [comment]
As a side note, we can't handle this as a special case in libversion as it will break ordering horribly. E.g. while `2018.01.01` < `12345.0` and `12345.0` < `20180101`, we can't treat dates equal out of blue.
