### ISSUE TITLE
Change meaning of `p` in versions

### ISSUE THREAD

**Issue by AMDmi3** [repology/libversion#4]
See repology/repology/issues/217. The hypothesis is that `p` is used in versions with the meaning of `patch`, not `pre`. Some statistics on `p` usage should be gathered from repology, and if it's true, it should be fixed to be handled like `patch`.

**Comment by blshkv** [comment]
sorry, this issue is not fixed completely for me. I'm looking at the following URL:
https://repology.org/metapackages/outdated-in-repo/gentoo_ovl_pentoo/

It shows that the following packages outdated but they actually ahead of it:
emilpro 3_p20170708  3
osslsigncode 1.7.1_p20150831 1.7.1
reaver-wps-fork-t6x 1.5.2_p20161210 1.5.2

Thank you for your work!

**Comment by AMDmi3** [comment]
These are bad examples as these are a snapshots and should just be ignored anyway.

The real case is [sudo](https://www.sudo.ws/) which uses ```pN``` suffix in official versions.

**Comment by blshkv** [comment]
well, according to Gentoo manual:
```
https://devmanual.gentoo.org/ebuild-writing/file-format/
_alpha < _beta < _pre < _rc < release < _p
```
so patch release should be ahead of the release.

**Comment by blshkv** [comment]
a new examples:
https://repology.org/metapackages/outdated-in-repo/gentoo_ovl_pentoo/

```<snapshot> vs <snapshot>_alpha```

For example, "libvshadow-alpha-20170715" is the official release name.
Can you fix it so it won't be shown as outdated?

**Comment by AMDmi3** [comment]
No, broken and ambigous upstream (and I mean both software projects and repositories here) versioning schemes cannot and will not be fixed in libversion.

Here 'alpha' it's not even part of the version. Tag is numeric, version in configure.ac is numeric, 'alpha' is only mentioned in release name and even there it preceeds version which suggests it's not a part of it. No other repo use this suffix either.

Also, there's no way `123_alpha` will be treated equal to `123`, because even though this scheme is strange without alpha number, it should still be ordered correctly with potential `123_beta`/rc/prerelease, all before plain `123`.

**Comment by AMDmi3** [comment]
`p` is used in both `pre` and `patch` meanings in the wild, an there's no way to teach libversion automatically guess which was implied. Instead, I've implemented a flag to control this behavior from the outside.
