### ISSUE TITLE
equivalent of prefixes

### ISSUE THREAD

**Issue by blshkv** [repology/libversion#7]
this is probably continuation of the bug https://github.com/repology/repology/issues/216

https://repology.org/metapackages/outdated-in-repo/gentoo_ovl_pentoo/
whatweb 0.4.8_pre20161009 (gentoo)  vs 0.4.8git20161009 (debian).
The package is marked as "newest known devel". But isn't it the same version?

**Comment by AMDmi3** [comment]
You can't know. `git` may either have "post" or "pre" meaning. And for `pre`, version is meaningless, as you may not know whether it will be 0.4.8, 0.4.7.1, 0.5.0 or 1.0.0 or whatever. Actually I was writing https://github.com/repology/repology/issues/345 for some days, let's move it there as it's not a libversion problem.

**Comment by blshkv** [comment]
```net-analyzer/whatweb-0.4.8_pre20161009```
```
bash$ whatweb --version
WhatWeb version 0.4.8-dev ( http://www.morningstarsecurity.com/research/whatweb/ )
```

**Comment by AMDmi3** [comment]
This is the very same guessing, but done by an author. It may happen that while 4.8 is deep in development stage, critical bug found in 4.7 would still require 4.7.1 release. Or it will be released as 4.8, making the situation even more complicated, as 4.8 will be closer to 4.7 than 4.8pre*.

**Comment by blshkv** [comment]
this is normal practice that upstream might maintain several trees 4.7.x stable and 4.8.x pre/stable.

Take capstone, for example:
https://github.com/aquynh/capstone/releases
They have seems maintain 3 lines:
 3.0.4 release, 3.0.5-rc5 and 4.0-alpha4

**Comment by AMDmi3** [comment]
Yes, but we're talking about single branch here.
